# Generated by Django 5.2 on 2026-03-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elective_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=5)),
            ],
        ),
    ]
